name: Update Submodules
env:
  BUILD_USER: ${{ secrets.BUILD_USER }}
  BUILD_USER_EMAIL:  ${{ secrets.BUILD_USER_EMAIL }}
on:
  push:
    branches: [ develop ]
  repository_dispatch:
    types: [dispatch-update-website]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup git user
        run: |
          git config --global user.email ${BUILD_USER_EMAIL}
          git config --global user.name ${BUILD_USER}
      - name: Shallow Clone with Submodules
        run: |
          git clone https://${{ github.token }}@github.com/${{ github.repository }}.git --recurse-submodules --single-branch .
      - name: update latest changes of devonfw-guide
        run: |
          cd devonfw-guide
          git checkout master
          git fetch
          git branch
          git merge origin/master
          cd ..
          git add devonfw-guide
          cd katacoda-scenarios/
          git checkout master
          git fetch
          git branch
          git merge origin/master
          cd ..
          git add katacoda-scenarios
          cd wiki-tutorials/
          git checkout main
          git fetch
          git branch
          git merge origin/main
          cd ..
          git add wiki-tutorials 
          cd solutions/
          git checkout master
          git fetch
          git branch
          git merge origin/master
          cd ..
          git add solutions
          
          # just commit if there is anything to commit
          git diff --cached --exit-code
          result=${?}
          if [ ${result} = 0 ]
          then
            echo "Nothing to commit!"
          else
            git commit -m "[DocUpdate]"
            git push origin develop
          fi
